import { StyleSheet } from "react-native"

export const appStyles = StyleSheet.create({
  root: { flex: 1, backgroundColor: "#05090d" },
  centered: { flex: 1, alignItems: "center", justifyContent: "center" },
  bottomScreenPad: {
    flex: 1,
    padding: 16,
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-end",
    paddingBottom: 56,
  },
  topScreenPad: {
    flex: 1,
    padding: 16,
    display: "flex",
    flexDirection: "column",
  },
  pager: { flex: 1 },
  page: { flex: 1 },
  title: {
    color: "#d8ffe9",
    fontSize: 28,
    fontWeight: "900",
    marginBottom: 8,
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  headerTitle: {
    color: "#d8ffe9",
    fontSize: 19,
    fontWeight: "800",
    letterSpacing: 0.7,
    textTransform: "uppercase",
  },
  subtitle: { color: "#72d8ad", fontSize: 14, marginBottom: 12 },
  label: {
    color: "#84a8b1",
    fontSize: 11,
    marginBottom: 4,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  muted: { color: "#84a8b1", fontSize: 12, marginBottom: 8 },
  body: { color: "#bfd5de", fontSize: 14, lineHeight: 20, marginBottom: 10 },
  progressOuter: {
    height: 8,
    backgroundColor: "#111a22",
    borderRadius: 999,
    overflow: "hidden",
    marginBottom: 8,
  },
  progressInner: { height: 8, backgroundColor: "#4df4aa" },
  button: {
    backgroundColor: "#0f171f",
    borderColor: "#284756",
    borderWidth: 1,
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 12,
    marginTop: 10,
    alignItems: "center",
    shadowColor: "#45f4ac",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.18,
    shadowRadius: 6,
  },
  primaryButton: { backgroundColor: "#42d995", borderColor: "#8bfec8" },
  buttonText: { color: "#d3e8ee", fontWeight: "700" },
  primaryButtonText: {
    color: "#042012",
    fontWeight: "900",
    letterSpacing: 0.4,
    textTransform: "uppercase",
  },
  rowBetween: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  row: { flexDirection: "row", gap: 8, marginBottom: 10 },
  smallButton: {
    backgroundColor: "#0f171f",
    borderColor: "#274758",
    borderWidth: 1,
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  smallButtonActive: { backgroundColor: "#42d995", borderColor: "#8bfec8" },
  smallButtonText: {
    color: "#d3e8ee",
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.4,
  },
  card: {
    backgroundColor: "#0c151d",
    borderColor: "#223a46",
    borderWidth: 1,
    padding: 12,
    borderRadius: 14,
    marginBottom: 10,
    shadowColor: "#43f4ab",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
  },
  cardLocked: { opacity: 0.55 },
  cardTitle: {
    color: "#d8ffe9",
    fontWeight: "700",
    fontSize: 15,
    marginBottom: 4,
  },
  warning: { color: "#ffc27e", fontSize: 12, marginTop: 4 },
  cipherBox: {
    backgroundColor: "#091512",
    borderColor: "#2f9472",
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
    marginBottom: 10,
  },
  cipherText: {
    color: "#77ffc2",
    fontSize: 16,
    fontWeight: "800",
    letterSpacing: 0.5,
  },
  input: {
    backgroundColor: "#0b141b",
    borderColor: "#24404f",
    borderWidth: 1,
    borderRadius: 12,
    color: "#d8ffe9",
    paddingVertical: 12,
    paddingHorizontal: 10,
    marginTop: 10,
  },
  hint: { color: "#8df2c1", fontSize: 13, marginTop: 10 },
  levelChip: {
    backgroundColor: "#0f171f",
    borderColor: "#274758",
    borderWidth: 1,
    borderRadius: 999,
    paddingVertical: 6,
    paddingHorizontal: 10,
    marginRight: 8,
  },
  levelChipActive: { backgroundColor: "#42d995", borderColor: "#8bfec8" },
  tabBar: {
    flexDirection: "row",
    backgroundColor: "#070f14",
    borderTopWidth: 1,
    borderTopColor: "#1e3744",
    paddingBottom: 12,
    paddingTop: 8,
    height: 72,
  },
  tabButton: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 8,
    gap: 4,
  },
  tabIcon: {
    fontSize: 24,
    marginBottom: 4,
    color: "#6d8b95",
  },
  tabIconActive: {
    color: "#6affbc",
  },
  tabLabel: {
    fontSize: 11,
    fontWeight: "600",
    color: "#6d8b95",
  },
  tabLabelActive: {
    color: "#6affbc",
  },
  statsGrid: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 10,
  },
  statCard: {
    flex: 1,
    backgroundColor: "#0c151d",
    borderColor: "#223a46",
    borderWidth: 1,
    borderRadius: 10,
    padding: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  statValue: {
    color: "#6affbc",
    fontSize: 20,
    fontWeight: "800",
    marginBottom: 4,
  },
  statLabel: {
    color: "#6d8b95",
    fontSize: 11,
    fontWeight: "600",
  },
  profileSection: {
    backgroundColor: "#0c151d",
    borderColor: "#223a46",
    borderWidth: 1,
    borderRadius: 10,
    padding: 12,
    marginBottom: 12,
  },
  profileValue: {
    color: "#d8ffe9",
    fontSize: 14,
    fontWeight: "600",
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.55)",
    justifyContent: "flex-end",
  },
  modalPanel: {
    backgroundColor: "#060d12",
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderColor: "#20404f",
    borderWidth: 1,
    padding: 16,
  },
  mapShell: {
    position: "relative",
    marginTop: 4,
    height: 390,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: "#3fe8a6",
    overflow: "hidden",
    backgroundColor: "#06121b",
    shadowColor: "#4ef4af",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.35,
    shadowRadius: 12,
  },
  mapPannerX: {
    flex: 1,
  },
  mapPannerXContent: {
    minWidth: "100%",
  },
  mapPannerY: {
    flex: 1,
  },
  mapPannerYContent: {
    minHeight: "100%",
  },
  mapCanvas: {
    position: "relative",
    backgroundColor: "#06121b",
  },
  mapImage: {
    flex: 1,
  },
  mapImageInner: {
    width: "100%",
    height: "100%",
  },
  mapBackdropBlobA: {
    position: "absolute",
    width: 420,
    height: 320,
    borderRadius: 999,
    backgroundColor: "rgba(17,92,129,0.5)",
    left: 120,
    top: 200,
  },
  mapBackdropBlobB: {
    position: "absolute",
    width: 500,
    height: 360,
    borderRadius: 999,
    backgroundColor: "rgba(7,62,91,0.55)",
    right: 80,
    bottom: 160,
  },
  mapMarker: {
    position: "absolute",
    transform: [{ translateX: -36 }, { translateY: -14 }],
    minWidth: 72,
    maxWidth: 132,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(170,245,214,0.95)",
    paddingVertical: 4,
    paddingHorizontal: 8,
  },
  mapMarkerSelected: {
    borderColor: "#6affbc",
    borderWidth: 2,
    shadowColor: "#6affbc",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.7,
    shadowRadius: 10,
  },
  mapMarkerLabel: {
    color: "#071318",
    fontSize: 10,
    fontWeight: "800",
    textAlign: "center",
  },
  mapSelectedBanner: {
    position: "absolute",
    left: 18,
    right: 18,
    top: 16,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#2e5765",
    backgroundColor: "rgba(5,14,20,0.88)",
    paddingVertical: 6,
    paddingHorizontal: 10,
  },
  mapSelectedText: {
    color: "#d8ffe9",
    fontSize: 12,
    fontWeight: "700",
    textAlign: "center",
  },
  mapCountryCard: {
    backgroundColor: "#0b141b",
    borderColor: "#2b4c5b",
    borderWidth: 1,
    borderRadius: 12,
    marginTop: 12,
    padding: 12,
  },
  mapHelpText: {
    color: "#79a5b3",
    fontSize: 12,
    marginTop: 12,
  },
  mapEnterText: {
    color: "#6affbc",
    fontSize: 12,
    fontWeight: "700",
    marginTop: 8,
  },
  devPanelWrap: {
    position: "absolute",
    right: 12,
    bottom: 96,
    width: 128,
  },
  devPanelBody: {
    marginTop: 8,
    backgroundColor: "rgba(7,14,19,0.97)",
    borderColor: "#315062",
    borderWidth: 1,
    borderRadius: 10,
    padding: 8,
  },
  devButton: {
    backgroundColor: "#10202b",
    borderColor: "#2c5568",
    borderWidth: 1,
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 8,
    marginTop: 6,
    alignItems: "center",
  },
  devHeaderButton: {
    marginTop: 0,
    backgroundColor: "#1b6b4f",
    borderColor: "#6cffbf",
  },
  devDangerButton: {
    backgroundColor: "#5c2a2a",
    borderColor: "#8a3f3f",
  },
  devButtonText: {
    color: "#d8ffe9",
    fontSize: 12,
    fontWeight: "700",
  },
  devMetaText: {
    color: "#79a5b3",
    fontSize: 11,
    marginBottom: 4,
  },
  levelUpBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.82)",
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
    zIndex: 120,
  },
  levelUpCard: {
    width: "100%",
    maxWidth: 340,
    backgroundColor: "#060d12",
    borderColor: "#2f9472",
    borderWidth: 1,
    borderRadius: 16,
    paddingVertical: 20,
    paddingHorizontal: 16,
    alignItems: "center",
  },
  levelUpTitle: {
    color: "#6affbc",
    fontSize: 30,
    fontWeight: "900",
    textTransform: "uppercase",
    marginBottom: 6,
  },
  levelUpSubtitle: {
    color: "#a7edcd",
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 18,
  },
  levelUpRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 14,
    marginBottom: 14,
  },
  levelUpStatBlock: {
    alignItems: "center",
    minWidth: 90,
  },
  levelUpLabel: {
    color: "#7da5af",
    fontSize: 10,
    textTransform: "uppercase",
    marginBottom: 2,
  },
  levelUpOldLevel: {
    color: "#c7d0d9",
    fontSize: 30,
    fontWeight: "800",
  },
  levelUpArrow: {
    color: "#6affbc",
    fontSize: 22,
    fontWeight: "800",
  },
  levelUpNewLevel: {
    color: "#ffffff",
    fontSize: 40,
    fontWeight: "900",
  },
  levelUpRankText: {
    color: "#6affbc",
    fontSize: 14,
    fontWeight: "700",
    textTransform: "uppercase",
    marginBottom: 10,
  },
  levelUpHint: {
    color: "#73939e",
    fontSize: 11,
  },
})
